AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'Prod'

Globals:
  Function:
    Runtime: python3.9
    Handler: index.handler
    Timeout: 10

Resources:

  # ============================================================
  # IAM
  # ============================================================

  ApiAuthInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: [ "apigateway.amazonaws.com" ]
            Action: [ sts:AssumeRole ]
      Policies:
        - PolicyName: "InvokeAuthorizerFunc"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                Resource: !GetAtt AuthorizerFunc.Arn

  # ============================================================
  # API GATEWAY
  # ============================================================

  ChatbotApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      Auth:
        DefaultAuthorizer: LambdaRequestAuthorizer
        Authorizers:
          LambdaRequestAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunc.Arn
            FunctionInvokeRole: !GetAtt ApiAuthInvokeRole.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true

  # ============================================================
  # LAMBDA
  # ============================================================

  # Authorizers

  AuthorizerFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/auth

  # Utils

  CoreFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/core
      Policies:
        - AmazonLexFullAccess
      Events:
        PostEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /core
            Method: any

  HelloFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/hello
      Events:
        AnyEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /hello
            Method: any
            Auth:
              Authorizer: NONE

  # Cultural events

  CulturalEventsCityFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/cultural_events_city
      Policies:
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess

      Events:
        PostEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /cultural_events_city
            Method: post


  CulturalEventsAddToCalendarFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/cultural_events_add_to_calendar
      Policies:
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess

      Events:
        PostEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /cultural_events_add_to_calendar
            Method: post
  # Events

  EventGetFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/events/get
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /events
            Method: get

  EventPostFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/events/post
      Events:
        PostEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /events
            Method: post

  # Tasks

  TaskPostFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/tasks/post
      Events:
        PostEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /tasks
            Method: post

  TaskGetFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/tasks/get
      Events:
        PostEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /tasks
            Method: get

  # Weather

  GetWeatherForEventFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/event_weather
      Policies:
        - AmazonDynamoDBFullAccess
        - SecretsManagerReadWrite
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /event_weather
            Method: get

  WeatherTodayFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/weather_today
      Policies:
        - SecretsManagerReadWrite
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /weather_today
            Method: get
            Auth:
              Authorizer: NONE

  WeatherDateFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gen/weather_date
      Policies:
        - SecretsManagerReadWrite
      Events:
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ChatbotApi
            Path: /weather_date
            Method: get
            Auth:
              Authorizer: NONE



Outputs:
  ChatbotApi:
    Description: "Chatbot API (endpoint for ensuring API is operational)"
    Value: !Sub "https://${ChatbotApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
